<?php 
// Enable error reporting
error_reporting(E_ALL);
ini_set('display_errors', 1);

// autoload.php generated by Composer
require __DIR__ . '/vendor/autoload.php';
if(isset($_GET['token']))
{

	$conn = @mysql_connect(MYSQL_SERVER,MYSQL_USER,MYSQL_PASS);
	if(! $conn ) 
	{
		echo('Could not connect: ' . mysql_error());
	}

	mysql_select_db(MYSQL_DB);

	$userid = 0;
	$retval = mysql_query( "SELECT id FROM ".MYSQL_DB.".uf_user where password='".$_GET['token']."'", $conn );
	while ($row = mysql_fetch_array($retval))
	{
		$userid = $row['id'];
		
		//echo "User Found</br>";
	}
	if (isset($_GET['updategoal'])&& is_numeric($_GET['updategoal'])&& $userid!=0)
	{
		$query = "SELECT * FROM ".MYSQL_DB.".Goals where userid='".$userid."' AND idGoals ='".$_GET['updategoal']."' ";

		$retval = mysql_query( $query , $conn );
		
		while ($row = mysql_fetch_array($retval))
		{
			//echo ("<hr>goal valid <hr>updating");
			$insert = true;
							$updatesql ="Insert into ".MYSQL_DB.".GoalCompletion (idGoal,submitted) VALUES";
				$updatesql.="(".$_GET['updategoal'].",NOW())";
				
				mysql_query( $updatesql, $conn );
				echo "<h1>Goal #[".$_GET['updategoal']."] was updated !</h1>";
				break;
		}
	
	}
	else
	echo "Goal not valid, or user is incorrect";
}

?>


